/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Testing
{
    public class array : Message
    {
        public const string RosMessageName = "testing/array";

        public int[] int_array { get; set; }

        public array()
        {
            this.int_array = new int[0];
        }

        public array(int[] int_array)
        {
            this.int_array = int_array;
        }
    }
}
